from langgraph.types import interrupt
from app.memory.memory_store import Memory_Functions
from app.core.logging.utils import log_node_execution, log_error, log_qa_session


def info_collector_node(state, config):
    """Pause the workflow to collect answers to the questions generated by question_generator_node.

    Deliberately does no LLM calls: LangGraph replays a node's code from the top on every
    resume from an interrupt inside it, so anything here must be safe to recompute identically
    every time. Question generation lives in question_generator_node (which runs before this
    node and completes normally, so it checkpoints once and is never replayed).
    """

    thread_id = config.get("configurable", {}).get("thread_id", "default")
    is_gift = bool(state.get("is_gift"))

    try:
        questions_data = state.get("generated_questions", [])
        questions = [q["question"] for q in questions_data]

        log_node_execution(thread_id, "Info Collector", f"Awaiting answers to {len(questions)} question(s)")

        # Use LangGraph interrupt to pause workflow and collect answers
        collected_answers = interrupt(questions)

        # Log Q&A session
        qa_pairs = [{"question": q, "answer": collected_answers.get(q, "")} for q in questions]
        log_qa_session(thread_id, qa_pairs)

        # Merge: profile-derived answers first, then explicit answers from this turn override them
        known_preferences = state.get("known_preferences") or {}
        merged_info = dict(known_preferences) if not is_gift else {}
        merged_info.update(collected_answers)
        state["collected_info"] = merged_info
        log_node_execution(thread_id, "Info Collector", f"Collected {len(collected_answers)} answers")

        # Persist newly-answered DURABLE preferences back to the profile (skip for gifts)
        if not is_gift:
            durability = state.get("question_durability", {})
            new_durable_facts = {
                q: a for q, a in collected_answers.items()
                if durability.get(q) and isinstance(a, str) and a.strip().lower() not in ("no", "none", "n/a", "")
            }
            if new_durable_facts:
                Memory_Functions.update_user_profile(new_durable_facts)
                log_node_execution(thread_id, "Info Collector", f"Saved {len(new_durable_facts)} durable preference(s) to profile")

        return state

    except Exception as e:
        # Ignore LangGraph interrupts, they are control flow signals
        if "GraphInterrupt" in str(type(e)):
            raise e

        log_error(thread_id, "Info Collector Node", e)
        raise
